services:
  postgres:
    container_name: postgres
    env_file:
      - ./.env
    image: postgres:16.2
    networks:
      - internal
    expose:
      - "5432"
    # ports:
    #  - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./build/init.sql:/docker-entrypoint-initdb.d/init.sql

  mlflow-service:
    # image: ghcr.io/mlflow/mlflow:v2.15.1
    image: ghcr.io/mlflow/mlflow:v3.11.1
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_BUCKET_NAME: ${DEFAULT_BUCKET_NAME}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      # AWS_DEFAULT_REGION: ru-central1
    command:
      - bash
      - -c
      - |
        pip install boto3 psycopg2-binary --quiet
        mlflow server --host 0.0.0.0 --port 5000 \
            --workers 1 \
            --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} \
            --default-artifact-root s3://mlflow-bucket/mlflow \
            --artifacts-destination s3://mlflow-bucket/mlflow \
            --cors-allowed-origins '*'
    expose:
      - "5000"
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_started
      mc:
        condition: service_completed_successfully
    volumes:
      # - mlflow-data:/mlflow
      - ./data/mlflow:/mlflow

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - '${S3_API_PORT}:9000'
      - '${S3_UI_PORT}:9001'
    volumes:
      - ./data/minio_data:/data
    env_file:
      - ./.env
    networks:
      - internal
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: always

  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: minio_mc
    volumes:
      - ./data/minio_data:/data
    env_file: "./.env"
    networks:
      - internal
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      if mc ls minio/${DEFAULT_BUCKET_NAME} > /dev/null 2>&1; then
        echo '${DEFAULT_BUCKET_NAME} already exists'
      else
        mc mb minio/${DEFAULT_BUCKET_NAME}
      fi
      "
    depends_on:
      minio:
        condition: service_healthy

volumes:
  mlflow-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mlflow_data
  minio_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/minio_data

networks:
  internal:
    driver: bridge