version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anomaly-detection-api
    ports:
      - "8080:8000"
    volumes:
      - db_data:/app/db_data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db_data:
